import type { User } from "../../../src/types/User.ts";

// every seeded account shares one password: admin
// a fixed hash keeps the seed deterministic (bcrypt salts are random by design).
// it is deliberately weaker than the rules new signups face — these are throwaway
// demo logins, not accounts anyone should trust
export const SEED_PASSWORD_HASH = "$2b$10$kaBupPzAjwf2awDLNWs1iulpTnzG2eXUvmapT0A0DIQPWG7FaG1fW";

// generated by scripts/generate-seed.ts — one university (newcastle), suburb
// coordinates averaged from the nsw address extract
export const seedUsers: User[] = [
  { id: "usr1", name: "Admin", email: "admin@pinch.edu.au", universityId: "pinch", role: "admin", verified: true, location: "Newcastle, NSW", lat: -32.9283, lng: 151.7817, createdAt: "2026-06-01T09:00:00.000Z" },
  { id: "usr2", name: "Priya S.", email: "priya.s@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Waratah West, NSW", lat: -32.89984, lng: 151.71284, createdAt: "2026-06-02T09:00:00.000Z" },
  { id: "usr3", name: "Daniel K.", email: "daniel.k@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Shortland, NSW", lat: -32.88125, lng: 151.69361, createdAt: "2026-06-03T09:00:00.000Z" },
  { id: "usr4", name: "Marco L.", email: "marco.l@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Carrington, NSW", lat: -32.9141, lng: 151.76714, createdAt: "2026-06-04T09:00:00.000Z" },
  { id: "usr5", name: "Aiko T.", email: "aiko.t@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Jesmond, NSW", lat: -32.90207, lng: 151.6929, createdAt: "2026-06-05T09:00:00.000Z" },
  { id: "usr6", name: "Hannah W.", email: "hannah.w@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Lambton, NSW", lat: -32.91375, lng: 151.70985, createdAt: "2026-06-06T09:00:00.000Z" },
  { id: "usr7", name: "Sam R.", email: "sam.r@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Islington, NSW", lat: -32.91508, lng: 151.74845, createdAt: "2026-06-07T09:00:00.000Z" },
  { id: "usr8", name: "Grace O.", email: "grace.o@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Wallsend, NSW", lat: -32.9036, lng: 151.67218, createdAt: "2026-06-08T09:00:00.000Z" },
  { id: "usr9", name: "Tom H.", email: "tom.h@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Merewether, NSW", lat: -32.94246, lng: 151.75065, createdAt: "2026-06-09T09:00:00.000Z" },
  { id: "usr10", name: "Nina P.", email: "nina.p@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Hamilton, NSW", lat: -32.92312, lng: 151.74567, createdAt: "2026-06-10T09:00:00.000Z" },
  { id: "usr11", name: "Leo M.", email: "leo.m@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Tighes Hill, NSW", lat: -32.90701, lng: 151.75219, createdAt: "2026-06-11T09:00:00.000Z" },
  { id: "usr12", name: "Omar F.", email: "omar.f@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Newcastle, NSW", lat: -32.92745, lng: 151.77745, createdAt: "2026-06-12T09:00:00.000Z" },
  { id: "usr13", name: "Ella B.", email: "ella.b@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Cooks Hill, NSW", lat: -32.93358, lng: 151.76781, createdAt: "2026-06-13T09:00:00.000Z" },
  { id: "usr14", name: "UoN Student Living", email: "living@uon.edu.au", universityId: "uon", role: "student", verified: true, orgType: "university", location: "Callaghan, NSW", lat: -32.89382, lng: 151.70429, createdAt: "2026-06-14T09:00:00.000Z" },
  { id: "usr15", name: "Hunter Street Property", email: "hello@hunterstreetproperty.com.au", universityId: "uon", role: "student", verified: true, orgType: "agency", location: "The Junction, NSW", lat: -32.93773, lng: 151.76019, createdAt: "2026-06-15T09:00:00.000Z" },
  { id: "usr16", name: "Nest & Key Realty", email: "hello@nestandkey.com.au", universityId: "uon", role: "student", verified: true, orgType: "agency", location: "New Lambton, NSW", lat: -32.92644, lng: 151.71325, createdAt: "2026-06-16T09:00:00.000Z" },
  { id: "usr17", name: "Coastline Lets", email: "rentals@coastlinelets.com.au", universityId: "uon", role: "student", verified: true, orgType: "agency", location: "Gosford, NSW", lat: -33.42588, lng: 151.34204, createdAt: "2026-06-17T09:00:00.000Z" },
  { id: "usr18", name: "Jess N.", email: "jess.n@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Ourimbah, NSW", lat: -33.35865, lng: 151.37134, createdAt: "2026-06-18T09:00:00.000Z" },
  { id: "usr19", name: "Ryan D.", email: "ryan.d@uon.edu.au", universityId: "uon", role: "student", verified: true, location: "Niagara Park, NSW", lat: -33.38321, lng: 151.35445, createdAt: "2026-06-19T09:00:00.000Z" },
  { id: "usr20", name: "Central Coast Student Living", email: "living.cc@uon.edu.au", universityId: "uon", role: "student", verified: true, orgType: "university", location: "Ourimbah, NSW", lat: -33.35865, lng: 151.37134, createdAt: "2026-06-20T09:00:00.000Z" },
];
